services:

  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
        - "8081:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    environment:
      DB_HOST: db
      DB_NAME: campus_app
      DB_USER: campus
      DB_PASSWORD: campus_password
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: campus_app
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
